name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fp_pso
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: fp_pso
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, mysql, xml, curl, gd
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Sesuaikan dengan versi Node.js yang dibutuhkan
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install # Ganti dengan `yarn install` jika menggunakan Yarn

      - name: Run Laravel Pint for linting
        run: ./vendor/bin/pint --test # --test akan memeriksa tanpa mengubah file, gagal jika ada pelanggaran

      - name: Build frontend assets
        run: npm run build # Ganti dengan `npm run prod` jika menggunakan Laravel Mix

      - name: Build backend (optimize)
        run: |
          cp .env.example .env.testing
          php artisan key:generate --env=testing
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run fresh migrations
        run: php artisan migrate:fresh --env=testing --force

      - name: Run database seeders
        run: php artisan db:seed --env=testing --force

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox
